//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImportOpenCNPJNet.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImportOpenCNPJNet.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to + Adicionar Arquivo.
        /// </summary>
        internal static string addFileBtn_Content {
            get {
                return ResourceManager.GetString("addFileBtn.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregar Metadados.
        /// </summary>
        internal static string btnLoadMetadata_Content {
            get {
                return ResourceManager.GetString("btnLoadMetadata.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testar Conexão ....
        /// </summary>
        internal static string connectbtn_Content {
            get {
                return ResourceManager.GetString("connectbtn.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha do Banco de Dados.
        /// </summary>
        internal static string dbPass_Header {
            get {
                return ResourceManager.GetString("dbPass.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço do Servidor.
        /// </summary>
        internal static string dbserver_Header {
            get {
                return ResourceManager.GetString("dbserver.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o Endereço do Servidor ....
        /// </summary>
        internal static string dbserver_PlaceholderText {
            get {
                return ResourceManager.GetString("dbserver.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Banco de Dados.
        /// </summary>
        internal static string dbtype_Header {
            get {
                return ResourceManager.GetString("dbtype.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o Tipo de Banco de Dados ....
        /// </summary>
        internal static string dbtype_PlaceholderText {
            get {
                return ResourceManager.GetString("dbtype.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usuário do Banco de Dados.
        /// </summary>
        internal static string dbUser_Header {
            get {
                return ResourceManager.GetString("dbUser.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digite o Usuário do Banco de Dados ....
        /// </summary>
        internal static string dbUser_PlaceholderText {
            get {
                return ResourceManager.GetString("dbUser.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arquivo a Importar.
        /// </summary>
        internal static string filePicker_Header {
            get {
                return ResourceManager.GetString("filePicker.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione o Arquivo a Importar ....
        /// </summary>
        internal static string filePicker_PlaceholderText {
            get {
                return ResourceManager.GetString("filePicker.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        internal static string ldMtDtCancelBtn_Content {
            get {
                return ResourceManager.GetString("ldMtDtCancelBtn.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregar Arquivo ....
        /// </summary>
        internal static string loadFileBtn_Content {
            get {
                return ResourceManager.GetString("loadFileBtn.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carregando Metadados de Arquivo.
        /// </summary>
        internal static string loadMetadataDialog_Title {
            get {
                return ResourceManager.GetString("loadMetadataDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banco de Dados.
        /// </summary>
        internal static string selectdb_Header {
            get {
                return ResourceManager.GetString("selectdb.Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecionar o Bando de Dados ....
        /// </summary>
        internal static string selectdb_PlaceholderText {
            get {
                return ResourceManager.GetString("selectdb.PlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Importação.
        /// </summary>
        internal static string startImportBtn_Content {
            get {
                return ResourceManager.GetString("startImportBtn.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1 - Configure o Banco de Dados.
        /// </summary>
        internal static string step1_Text {
            get {
                return ResourceManager.GetString("step1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 2 - Adicione os Arquivos.
        /// </summary>
        internal static string step2_Text {
            get {
                return ResourceManager.GetString("step2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 3 - Configurações Finais e Importação.
        /// </summary>
        internal static string step3_Text {
            get {
                return ResourceManager.GetString("step3.Text", resourceCulture);
            }
        }
    }
}
